/**
 * WebSocket broadcast tests (AUTO-GENERATED)
 *
 * Generated by: component-test-generation v1.0
 * Run: test-generation/ctg-20260608-171545
 * Closes: CTA-GAP-004 (WebSocket broadcast on /api/bridge/message)
 * Source: src/server.js
 *
 * Test approach: start the server on an ephemeral port, connect a ws client, POST to
 * /api/bridge/message, assert the broadcast arrives on the ws client.
 *
 * Note: server-ws.test.js is a NEW test file (the analysis's recommended target).
 *
 * DO NOT EDIT this header — the generator relies on it for audit.
 */

import { jest, beforeAll, afterAll, describe, it, expect } from '@jest/globals';
import request from 'supertest';
import { WebSocket } from 'ws';

let serverModule, closeDatabase, app, httpServer;
let authCookie;
let wsClient;
let port;

beforeAll(async () => {
  process.env.CTI_DB_PATH = ':memory:';
  serverModule = await import('../src/server.js');
  app = serverModule.app;
  httpServer = serverModule.server;
  closeDatabase = serverModule.closeDatabase;
  const db = await import('../src/db.js');
  db.initializeDatabase();

  // Register + log in
  await request(app)
    .post('/api/auth/register')
    .send({ username: 'ws_user', email: 'ws@example.com', password: 'wspassword123' });
  const loginRes = await request(app)
    .post('/api/auth/login')
    .send({ username: 'ws_user', password: 'wspassword123' });
  expect(loginRes.status).toBe(200);
  authCookie = loginRes.headers['set-cookie'][0];

  // Start the HTTP server on an ephemeral port. The wss is bound to this server.
  await new Promise((resolve) => {
    httpServer.listen(0, '127.0.0.1', () => {
      port = httpServer.address().port;
      resolve();
    });
  });

  // Open a WebSocket client connection
  wsClient = new WebSocket(`ws://127.0.0.1:${port}/ws`);
  await new Promise((resolve, reject) => {
    wsClient.on('open', resolve);
    wsClient.on('error', reject);
  });
}, 15000);

afterAll(async () => {
  if (wsClient && wsClient.readyState === WebSocket.OPEN) {
    wsClient.close();
  }
  if (httpServer && httpServer.listening) {
    await new Promise((resolve) => httpServer.close(resolve));
  }
  if (closeDatabase) closeDatabase();
}, 15000);

function nextWsMessage(timeoutMs = 2000) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      wsClient.off('message', onMsg);
      reject(new Error(`no ws message within ${timeoutMs}ms`));
    }, timeoutMs);
    function onMsg(data) {
      clearTimeout(timer);
      wsClient.off('message', onMsg);
      try { resolve(JSON.parse(data.toString())); } catch { resolve(data.toString()); }
    }
    wsClient.on('message', onMsg);
  });
}

describe('WebSocket broadcast (auto: CTA-GAP-004)', () => {
  it('broadcasts exchange_created event to ws clients when POST /api/bridge/message succeeds', async () => {
    const messagePromise = nextWsMessage(3000);

    const res = await request(app)
      .post('/api/bridge/message')
      .set('Cookie', authCookie)
      .send({
        exchangeType: 'task',
        subject: 'ws-broadcast-test',
        content: 'Test exchange for WebSocket broadcast coverage'
      });

    expect(res.status).toBe(201);
    const exchange = res.body;
    expect(exchange).toHaveProperty('id');
    expect(exchange.subject).toBe('ws-broadcast-test');

    const msg = await messagePromise;
    expect(msg).toHaveProperty('type', 'exchange_created');
    expect(msg).toHaveProperty('data');
    expect(msg.data).toHaveProperty('id', exchange.id);
    expect(msg.data).toHaveProperty('subject', 'ws-broadcast-test');
  }, 10000);

  it('does NOT broadcast anything when POST /api/bridge/message fails validation', async () => {
    // Subscribe to the next message; expect a timeout instead of a broadcast.
    const timeoutPromise = new Promise((_, reject) =>
      setTimeout(() => reject(new Error('expected no broadcast for invalid request')), 1500)
    );
    const messagePromise = nextWsMessage(2000).catch(() => null);

    const res = await request(app)
      .post('/api/bridge/message')
      .set('Cookie', authCookie)
      .send({ /* missing required fields */ });

    expect(res.status).toBe(400);

    // Race: if a message arrives, the test fails. If timeout fires, that's the expected behavior.
    const result = await Promise.race([messagePromise, timeoutPromise]).catch((e) => e);
    if (result && typeof result === 'object' && result.type) {
      throw new Error(`Unexpected broadcast for invalid request: ${JSON.stringify(result)}`);
    }
  }, 10000);
});
